# fly.toml app configuration file generated for babuji on 2024-01-14T13:56:56+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "babuji"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
